### ISSUE TITLE
config.ini - Parameter in Quotes

### ISSUE THREAD

**Issue by stvogel** [retconx/gerigdt#2]
Vielen Dank für das sehr hilfreiche Tool und gleichzeitig auch eine gute Vorlage für die GDT-Anbindung.

Im config.ini steht das "Geriatrisches Basisassessment" in Anführungszeichen - damit wird es auch mit "" bei der Einrichtung der Einstellungen vorgeschlagen (sind also quasi doppelt).

**Comment by retconx** [comment]
Danke für die Rückmeldung.
Der Fehler ist bekannt und wird mit dem nächsten Update behoben sein.
